### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by NathanNeelis** [RooyyDoe/real-time-web-2021#1]
### Scan your buddy's repository
* [x] Does the repo have an apt description?
* [x] Is there a link to the live demo at the top?
* [x] Are any files in the repo that shouldn't be there like a .env file or node_modules? 

> nope

* [x] Is there a section about the concept, install notes, data life cycle, external API, and real-time events?

> Ja, maar die moeten nog wel gevuld worden met informatie

### Try to understand the concept
* [x] Read about the concept in the readme, do you understand what the app does?
* [x] Open up the live link (if it's already alive) and play around with the app
* [x] Review the app's functions in an issue, feel free to add cool new ideas in an issue

> De app werkt super goed, nice! Een klein beetje feedback: Iets meer aanvullende tekst welke actie van de gebruiker required is. Bijvoorbeeld; kies een pokemon. En als je attacked zou het super nice zijn als je dat ook in de image ziet welke damage je doet.

* [x] Test the app in multiple tabs, does multi-user functionality work as expected?

>  Jaa! super gaaf dit. 

### Understand the data life cycle
* [x] Are all the app's components present in a visual diagram?
* [x] Is it clear what data is stored for each component?
* [x] Is it clear how components communicate with each other? (socket, polling, OAuth)
* [x] Can you follow where real-time data is created?

> Goed vormgegeven en zeer uitgebruid beschreven. Het enige wat ik nog even zou kunnen opmerken is dat je misschien de real time events nog even zou kunnen highlighten voor het overzicht. Maar als je het gewoon leest is het heel duidelijk. Ga ik een voorbeeld aan nemen!

### Check the real-time events
* [x] Are all custom events described?
* [x] Can you imagine how the client-server communication works now that you know which events are used?

> Nog toevoegen aan je readme, maar wat ik uit je datalifecycle diagram haal, wordt dit geen probleem. Aangezien het daar ook al uitvoerig in beschreven wordt.

### Review the API info
* [x] Is it clear what data the external API offers?
* [x] Are instructions present on how to get a key from the API and how to connect to it?

> Hier zou je nog wat mee kunnen doen. Je beschrijft het al kort in je datalife cycle. Misschien even wat extra info aan toevoegen in de readme API.

#### Code

> Even door wat van je code heen gelopen, ziet er super goed uit. Echt heel veel ook! Goed bezig! En fijne comments ook in je code, dan kan ik goed je code flow begrijpen.

**Comment by RooyyDoe** [comment]
Fixed all the things that I did not have thanks! :)
