### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by Jelmerovereem** [RooyyDoe/real-time-web-2021#14]
Top dat je al zoveel mogelijk met modules werkt!
Maar je zou je [client-side main.js](https://github.com/RooyyDoe/Poke-Fight/blob/master/public/js/main.js) nog wel meer kunnen opdelen in modules.

**Comment by RooyyDoe** [comment]
Voor nu laat ik het zo, maar in mijn volgende project neem ik dit zeker mee thanks! 👍
