### ISSUE TITLE
feedback aan user geven wanneer user pokémon aan het zoeken is

### ISSUE THREAD

**Issue by Jelmerovereem** [RooyyDoe/real-time-web-2021#2]
Als de gebruiker een pokémon zoekt komt er nu geen feedback of het zoeken bezig is of is mislukt.
Gebruiker weet ook niet welke pokémons nu er allemaal kiesbaar zijn.(ik snap dat nog niet alle pokémons zijn geïmplementeerd)

**Comment by RooyyDoe** [comment]
Error message toegevoegd!
