### ISSUE TITLE
nadat de battle is afgelopen wat feedback toevoegen

### ISSUE THREAD

**Issue by Jelmerovereem** [RooyyDoe/real-time-web-2021#5]
Zodra de battle is afgelopen is het niet heel duidelijk wat de gebruiker kan doen. Wordt hij/zij terug geleid naar de gym? Of moet je inderdaad weer op start battle drukken.

**Comment by RooyyDoe** [comment]
Victory / Defeat screen toegevoegd! thanks 
<img width="1440" alt="Schermafbeelding 2021-04-27 om 18 59 14" src="https://user-images.githubusercontent.com/40355914/116282153-b80b3600-a78a-11eb-92ab-18c1a848d3f7.png">
<img width="1440" alt="Schermafbeelding 2021-04-27 om 18 59 23" src="https://user-images.githubusercontent.com/40355914/116282167-bb9ebd00-a78a-11eb-949b-0a78d769dbc4.png">
