### ISSUE TITLE
tegen jezelf spelen?

### ISSUE THREAD

**Issue by Jelmerovereem** [RooyyDoe/real-time-web-2021#6]
Ik ging een beetje spammen op de "start battle" knop en nu zit ik in een potje met mezelf 🤣 
![image](https://user-images.githubusercontent.com/58043913/115842640-52cbe380-a41e-11eb-90e4-87ec1ddf6312.png)

**Comment by RooyyDoe** [comment]
Fixed! thanks 🗡️
