### ISSUE TITLE
zit met een client/speler in een battle die al niet meer in de app zit

### ISSUE THREAD

**Issue by Jelmerovereem** [RooyyDoe/real-time-web-2021#8]
![image](https://user-images.githubusercontent.com/58043913/115843277-f3220800-a41e-11eb-9940-823af436a416.png)
Zoals je hier ziet zitten speler1 en speler2 in de battle. Maar je ziet onderaan dat jelmer starts... Dus die client zit er op een of andere manier nog in.

**Comment by RooyyDoe** [comment]
Deze bug komt echt heel random en kan hem niet precies vinden.. Hoe kreeg je deze precies?

**Comment by RooyyDoe** [comment]
Volgens mij heb ik de bug gefixt! :)
